### ISSUE TITLE
converting MAT file to .SGY

### ISSUE THREAD

**Issue by rachelPython** [cultpenguin/segymat#2]
Hey,
I couldn't find in this package a way of doing this conversion,
Is there a solution ?

Thanks,

**Comment by cultpenguin** [comment]
This is exactly what SegyMAT is for.
See the first example in
https://segymat.readthedocs.io/en/latest/segywriting.html

load data.mat
WriteSegy('datacube.segy',data, 'dt',.004)

- THomas

**Comment by rachelPython** [comment]
Thank you very much ! In with units the 'dt' need to be inserted to this function?
because i see there is a multiplication by 1*10^6 inside the function

**Comment by cultpenguin** [comment]
I believe dt should be in seconds.

**Comment by rachelPython** [comment]
Thank you.
I would like to make sure that the deafult format is **new floating point 32bit** ?
because its the deafult format for all global uses

**Comment by cultpenguin** [comment]
If you use revision 1 and 'DataSampleFormat' 5, the data is formatted in
IEEE 32 bit.

See detail in the "DataSampleFormat" section in
https://segymat.readthedocs.io/en/latest/format.html

You can force the use of this format using

  D=ReadSegy(filename,'revision',1,'dsf',5);

Have a nice day
- Thomas

**Comment by rachelPython** [comment]
Hi,
Thank you for your answer. I'm trying to convert .mat file (Matlab) to a .sgy file. 
Now I need to open the .sgy file on REFLEX-W and I'm having a problem...
I see that the original file dimentions are changed , and REFLEX-W  can't open this file. 
I get this error message, while I'm using the format you mentioned (float32)
![image](https://user-images.githubusercontent.com/47176720/59287230-edcbd200-8c79-11e9-9ee6-774f3c0a21d6.png)

**Comment by cultpenguin** [comment]
I do not not the REFLEX-W software. I suggest you try some of the other
support data sample formats and see if the should work with RELFEX-W.
Have a nice day
- Thomas

**Comment by cultpenguin** [comment]
Nothing new for long time in this thread so it is closed
